// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksEvaluation.Infrastructure.Data;

#nullable disable

namespace TasksEvaluation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240328001404_INITDataBase")]
    partial class INITDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Common.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bases");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Assignment", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GroupId");

                    b.ToTable("Bases", t =>
                        {
                            t.Property("GroupId")
                                .HasColumnName("Assignment_GroupId");

                            t.Property("Title")
                                .HasColumnName("Assignment_Title");
                        });

                    b.HasDiscriminator().HasValue("Assignment");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Course", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Bases", t =>
                        {
                            t.Property("Title")
                                .HasColumnName("Course_Title");
                        });

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.EvaluationGrade", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("EvaluationGrade");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Group", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Solution", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasFilter("[AssignmentId] IS NOT NULL");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentId");

                    b.HasDiscriminator().HasValue("Solution");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Student", b =>
                {
                    b.HasBaseType("TasksEvaluation.Core.Entities.Common.Base");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GroupId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Assignment", b =>
                {
                    b.HasOne("TasksEvaluation.Core.Entities.Business.Group", null)
                        .WithMany("Assignments")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Group", b =>
                {
                    b.HasOne("TasksEvaluation.Core.Entities.Business.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Solution", b =>
                {
                    b.HasOne("TasksEvaluation.Core.Entities.Business.Assignment", "Assignment")
                        .WithOne("Solution")
                        .HasForeignKey("TasksEvaluation.Core.Entities.Business.Solution", "AssignmentId");

                    b.HasOne("TasksEvaluation.Core.Entities.Business.EvaluationGrade", "Grade")
                        .WithMany("Solutions")
                        .HasForeignKey("GradeId");

                    b.HasOne("TasksEvaluation.Core.Entities.Business.Student", "Student")
                        .WithMany("Solutions")
                        .HasForeignKey("StudentId");

                    b.Navigation("Assignment");

                    b.Navigation("Grade");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Student", b =>
                {
                    b.HasOne("TasksEvaluation.Core.Entities.Business.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Assignment", b =>
                {
                    b.Navigation("Solution");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.EvaluationGrade", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Group", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("TasksEvaluation.Core.Entities.Business.Student", b =>
                {
                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
